### PR TITLE
Changing the text templates headlines

### PR DESCRIPTION
**Pull request by jyh947**
One of the pieces of feedback from the CalHacks Hackathon was that finding these layouts was fairly difficult.  We should make the discovery of these layouts easier.

### CODE REVIEW

**Comment by joeljfischer** [comment]
This is a good change. Thank you!

**Comment by jyh947** [comment]
Just a heads up, one of the changes that I want to implement is to show some code for each template.  For example, for the "Tiles only" layout, it could look like:
##### TILES_ONLY
##### Objective-C
```objc
SDLSetDisplayLayout* display = [[SDLSetDisplayLayout alloc] initWithPredefinedLayout:SDLPredefinedLayoutTilesOnly];
```

##### Swift
```swift
let display = SDLSetDisplayLayout(predefinedLayout: .tilesOnly)
```
###### Ford HMI
Tiles Only

##### GRAPHIC_WITH_TILES
###### Ford HMI
Graphic with Tiles


What are your thoughts?  This would be also changed in the Android guides.

**Comment by joeljfischer** [comment]
I think that as long as we give an example of doing it once, I don't know that we need code for every template.

**Comment by joeljfischer** [comment]
The important thing is clarity. As long as we make it clear how to do it. I'm worried that that much code will clutter an already kind of cluttered document.

**Comment by jyh947** [comment]
The issue that I saw at the hackathon was that teams didn't know how to find the predefinedLayout definitions.  It would be most useful if we could somehow have a list of all the predefinedlayouts in both Swift and Objective C. In my example, it's not 100% clear that TILES_ONLY is actually .tilesOnly in Swift.

**Comment by joeljfischer** [comment]
I gotcha, having a list in code blocks might be easier

```swift
.tilesOnly
```
like so.

Though in swift it should be quite easy since they can just use `SDLPredefinedLayout.` and the autocomplete should come up with all of their options.

**Pull request merged**
